services:
  inference_service:
    image: etl-senthelp-inference
    build:
      context: .
      dockerfile: Files/Dockerfile
    command: python ./inference_continue.py
    volumes:
      - .:/usr/local/airflow/